// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthUser struct {
	Guid              uuid.UUID
	Email             string
	PasswordHash      string
	Created           time.Time
	Updated           time.Time
	IsActive          bool
	VerificationToken sql.NullString
}
