// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, db DBTX, arg ActivateUserParams) error
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (AuthUser, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (AuthUser, error)
	GetUserByGUID(ctx context.Context, db DBTX, guid uuid.UUID) (AuthUser, error)
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) error
	UpdateVerificationToken(ctx context.Context, db DBTX, arg UpdateVerificationTokenParams) error
}

var _ Querier = (*Queries)(nil)
