// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package auth

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthSession struct {
	ID        uuid.UUID
	Secret    string
	UserGuid  uuid.UUID
	Created   time.Time
	Ip        string
	UserAgent string
	Active    sql.NullBool
	Nonce     sql.NullString
}
