// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package auth

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (AuthSession, error)
	GetActiveSessionByUserGUID(ctx context.Context, db DBTX, userGuid uuid.UUID) (AuthSession, error)
	GetSessionByID(ctx context.Context, db DBTX, id uuid.UUID) (AuthSession, error)
	GetSessions(ctx context.Context, db DBTX) ([]AuthSession, error)
	InvalidateSession(ctx context.Context, db DBTX, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
