version: "3.9"

services:
  hr-minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9001:9000
      - 9091:9090
    volumes:
      - ~/minio/data:/data
      - ~/work/cert/minio:/root/.minio/certs
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$
      - MINIO_DOMAIN=localhost:9000
    networks:
      - localnet

  hr-victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8430:8428"  # Порт для доступа к VictoriaMetrics
    command:
      - '-retentionPeriod=30'  # Период хранения данных в днях
    volumes:
      - victoria-metrics-data:/victoria-metrics-data  # Для хранения данных
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail http://localhost:8428/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - localnet

  hr-postgres:
    container_name: hr-postgres-container
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data 777
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - localnet

  platform-service:
    build:
      context: ./platform_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=hr-postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_SSLMODE=disable
      - MINIO_ENDPOINT=hr-minio:9001
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=Secure123$
      - MINIO_USE_SSL=false
      - MINIO_BUCKET=cv
    depends_on:
      - hr-postgres
      - hr-minio
      - hr-victoria-metrics
    networks:
      - localnet

networks:
  localnet:
    driver: bridge

x-environment:
  COMPOSE_PROJECT_NAME: hr_open_platform

volumes:
  victoria-metrics-data: