// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package job

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type JobJob struct {
	ID             uuid.UUID
	Title          string
	CompanyName    string
	Location       string
	EmploymentType string
	SalaryFrom     sql.NullInt32
	SalaryTo       sql.NullInt32
	Description    string
	Requirements   string
	AuthorID       uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Status         string
}

type JobJobApplication struct {
	ID          uuid.UUID
	JobID       uuid.UUID
	ApplicantID uuid.UUID
	AppliedAt   time.Time
	Status      string
}
