// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package job

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckJobExists(ctx context.Context, db DBTX, id uuid.UUID) (bool, error)
	CreateJob(ctx context.Context, db DBTX, arg CreateJobParams) (JobJob, error)
	CreateJobApplication(ctx context.Context, db DBTX, arg CreateJobApplicationParams) (JobJobApplication, error)
	DeleteJob(ctx context.Context, db DBTX, arg DeleteJobParams) error
	GetApplicationsCount(ctx context.Context, db DBTX, jobID uuid.UUID) (int64, error)
	GetJobApplication(ctx context.Context, db DBTX, arg GetJobApplicationParams) (JobJobApplication, error)
	GetJobApplications(ctx context.Context, db DBTX, arg GetJobApplicationsParams) ([]GetJobApplicationsRow, error)
	GetJobByID(ctx context.Context, db DBTX, id uuid.UUID) (JobJob, error)
	GetJobs(ctx context.Context, db DBTX, arg GetJobsParams) ([]JobJob, error)
	GetJobsByAuthor(ctx context.Context, db DBTX, arg GetJobsByAuthorParams) ([]GetJobsByAuthorRow, error)
	UpdateJob(ctx context.Context, db DBTX, arg UpdateJobParams) (JobJob, error)
	UpdateJobApplicationStatus(ctx context.Context, db DBTX, arg UpdateJobApplicationStatusParams) (JobJobApplication, error)
}

var _ Querier = (*Queries)(nil)
