// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package chat

import (
	"time"

	"github.com/google/uuid"
)

type ChatChat struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChatMessage struct {
	ID        uuid.UUID
	ChatID    uuid.UUID
	UserID    uuid.UUID
	Text      string
	CreatedAt time.Time
}
