// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package chat

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToChat(ctx context.Context, db DBTX, arg AddUserToChatParams) error
	CreateChat(ctx context.Context, db DBTX) (ChatChat, error)
	CreateMessage(ctx context.Context, db DBTX, arg CreateMessageParams) (ChatMessage, error)
	GetChatByID(ctx context.Context, db DBTX, id uuid.UUID) (GetChatByIDRow, error)
	GetChatByUsersIDs(ctx context.Context, db DBTX, arg GetChatByUsersIDsParams) (ChatChat, error)
	GetChatMessages(ctx context.Context, db DBTX, arg GetChatMessagesParams) ([]ChatMessage, error)
	GetLastMessage(ctx context.Context, db DBTX, chatID uuid.UUID) (ChatMessage, error)
	GetUnreadCount(ctx context.Context, db DBTX, arg GetUnreadCountParams) (int64, error)
	GetUserChats(ctx context.Context, db DBTX, userID uuid.UUID) ([]GetUserChatsRow, error)
	UpdateChatUpdatedAt(ctx context.Context, db DBTX, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
