// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package company

import (
	"database/sql"

	"github.com/google/uuid"
)

type CompanyCompany struct {
	Guid          uuid.UUID
	Name          string
	Description   sql.NullString
	Email         sql.NullString
	Phone         sql.NullString
	Website       sql.NullString
	Address       sql.NullString
	Avatar        sql.NullString
	ShortLinkName sql.NullString
}

type CompanyProfileCompany struct {
	UserGuid    uuid.UUID
	CompanyGuid uuid.UUID
	Position    string
	StartedAt   sql.NullTime
	FinishedAt  sql.NullTime
}
