// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package company

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCompany(ctx context.Context, db DBTX, arg CreateCompanyParams) (CompanyCompany, error)
	CreateProfileCompany(ctx context.Context, db DBTX, arg CreateProfileCompanyParams) (CompanyProfileCompany, error)
	DeleteCompany(ctx context.Context, db DBTX, guid uuid.UUID) error
	DeleteExperience(ctx context.Context, db DBTX, arg DeleteExperienceParams) error
	DeleteProfileCompany(ctx context.Context, db DBTX, arg DeleteProfileCompanyParams) error
	GetCompanyByGUID(ctx context.Context, db DBTX, guid uuid.UUID) (CompanyCompany, error)
	GetCompanyByShortLink(ctx context.Context, db DBTX, shortLinkName sql.NullString) (CompanyCompany, error)
	GetProfileCompanies(ctx context.Context, db DBTX, userGuid uuid.UUID) ([]CompanyProfileCompany, error)
	GetProfileCompany(ctx context.Context, db DBTX, arg GetProfileCompanyParams) (CompanyProfileCompany, error)
	SearchCompanies(ctx context.Context, db DBTX, dollar_1 sql.NullString) ([]CompanyCompany, error)
	UpdateCompany(ctx context.Context, db DBTX, arg UpdateCompanyParams) (CompanyCompany, error)
	UpdateProfileCompany(ctx context.Context, db DBTX, arg UpdateProfileCompanyParams) error
}

var _ Querier = (*Queries)(nil)
