// Package call provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package call

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CallStatus.
const (
	Active CallStatus = "active"
	Ended  CallStatus = "ended"
)

// Defines values for HandleWebSocketParamsConnection.
const (
	Upgrade HandleWebSocketParamsConnection = "upgrade"
)

// Defines values for HandleWebSocketParamsUpgrade.
const (
	Websocket HandleWebSocketParamsUpgrade = "websocket"
)

// Defines values for HandleWebSocketParamsSecWebSocketVersion.
const (
	N13 HandleWebSocketParamsSecWebSocketVersion = "13"
)

// Call defines model for Call.
type Call struct {
	CreatedAt    time.Time         `json:"created_at"`
	EndedAt      *time.Time        `json:"ended_at"`
	Id           string            `json:"id"`
	Participants []CallParticipant `json:"participants"`
	Status       CallStatus        `json:"status"`
}

// CallStatus defines model for Call.Status.
type CallStatus string

// CallParticipant defines model for CallParticipant.
type CallParticipant struct {
	Avatar      *string `json:"avatar"`
	Description string  `json:"description"`
	Id          string  `json:"id"`
}

// CallWithTranscript defines model for CallWithTranscript.
type CallWithTranscript struct {
	Call       Call              `json:"call"`
	Transcript []TranscriptEntry `json:"transcript"`
}

// CreateCallRequest defines model for CreateCallRequest.
type CreateCallRequest struct {
	Participants []string `json:"participants"`
}

// TranscriptEntry defines model for TranscriptEntry.
type TranscriptEntry struct {
	Text      string          `json:"text"`
	Timestamp time.Time       `json:"timestamp"`
	User      CallParticipant `json:"user"`
}

// GetCallHistoryParams defines parameters for GetCallHistory.
type GetCallHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// HandleWebSocketParams defines parameters for HandleWebSocket.
type HandleWebSocketParams struct {
	Token               string                                   `form:"token" json:"token"`
	Connection          HandleWebSocketParamsConnection          `json:"Connection"`
	Upgrade             HandleWebSocketParamsUpgrade             `json:"Upgrade"`
	SecWebSocketVersion HandleWebSocketParamsSecWebSocketVersion `json:"Sec-WebSocket-Version"`
	SecWebSocketKey     string                                   `json:"Sec-WebSocket-Key"`
}

// HandleWebSocketParamsConnection defines parameters for HandleWebSocket.
type HandleWebSocketParamsConnection string

// HandleWebSocketParamsUpgrade defines parameters for HandleWebSocket.
type HandleWebSocketParamsUpgrade string

// HandleWebSocketParamsSecWebSocketVersion defines parameters for HandleWebSocket.
type HandleWebSocketParamsSecWebSocketVersion string

// CreateCallJSONRequestBody defines body for CreateCall for application/json ContentType.
type CreateCallJSONRequestBody = CreateCallRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create new call
	// (POST /api/v1/call)
	CreateCall(w http.ResponseWriter, r *http.Request)
	// Get call history with transcripts
	// (GET /api/v1/call/history)
	GetCallHistory(w http.ResponseWriter, r *http.Request, params GetCallHistoryParams)
	// WebSocket connection for real-time video call and speech recognition
	// (GET /api/v1/call/{call_id}/ws)
	HandleWebSocket(w http.ResponseWriter, r *http.Request, callId string, params HandleWebSocketParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create new call
// (POST /api/v1/call)
func (_ Unimplemented) CreateCall(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get call history with transcripts
// (GET /api/v1/call/history)
func (_ Unimplemented) GetCallHistory(w http.ResponseWriter, r *http.Request, params GetCallHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WebSocket connection for real-time video call and speech recognition
// (GET /api/v1/call/{call_id}/ws)
func (_ Unimplemented) HandleWebSocket(w http.ResponseWriter, r *http.Request, callId string, params HandleWebSocketParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCall operation middleware
func (siw *ServerInterfaceWrapper) CreateCall(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCall(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCallHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCallHistory(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCallHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCallHistory(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleWebSocket operation middleware
func (siw *ServerInterfaceWrapper) HandleWebSocket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "call_id" -------------
	var callId string

	err = runtime.BindStyledParameterWithOptions("simple", "call_id", chi.URLParam(r, "call_id"), &callId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "call_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleWebSocketParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Connection" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Connection")]; found {
		var Connection HandleWebSocketParamsConnection
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Connection", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Connection", valueList[0], &Connection, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Connection", Err: err})
			return
		}

		params.Connection = Connection

	} else {
		err := fmt.Errorf("Header parameter Connection is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Connection", Err: err})
		return
	}

	// ------------- Required header parameter "Upgrade" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Upgrade")]; found {
		var Upgrade HandleWebSocketParamsUpgrade
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Upgrade", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Upgrade", valueList[0], &Upgrade, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Upgrade", Err: err})
			return
		}

		params.Upgrade = Upgrade

	} else {
		err := fmt.Errorf("Header parameter Upgrade is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Upgrade", Err: err})
		return
	}

	// ------------- Required header parameter "Sec-WebSocket-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Sec-WebSocket-Version")]; found {
		var SecWebSocketVersion HandleWebSocketParamsSecWebSocketVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Sec-WebSocket-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Sec-WebSocket-Version", valueList[0], &SecWebSocketVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Sec-WebSocket-Version", Err: err})
			return
		}

		params.SecWebSocketVersion = SecWebSocketVersion

	} else {
		err := fmt.Errorf("Header parameter Sec-WebSocket-Version is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Sec-WebSocket-Version", Err: err})
		return
	}

	// ------------- Required header parameter "Sec-WebSocket-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Sec-WebSocket-Key")]; found {
		var SecWebSocketKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Sec-WebSocket-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Sec-WebSocket-Key", valueList[0], &SecWebSocketKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Sec-WebSocket-Key", Err: err})
			return
		}

		params.SecWebSocketKey = SecWebSocketKey

	} else {
		err := fmt.Errorf("Header parameter Sec-WebSocket-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Sec-WebSocket-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleWebSocket(w, r, callId, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/call", wrapper.CreateCall)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/call/history", wrapper.GetCallHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/call/{call_id}/ws", wrapper.HandleWebSocket)
	})

	return r
}
