// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package call

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CallCall struct {
	ID        uuid.UUID
	CreatedAt time.Time
	EndedAt   sql.NullTime
	Status    string
}

type CallTranscript struct {
	ID        uuid.UUID
	CallID    uuid.UUID
	UserID    uuid.UUID
	Text      string
	Timestamp time.Time
}
