// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package call

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipantToCall(ctx context.Context, db DBTX, arg AddParticipantToCallParams) error
	AddTranscript(ctx context.Context, db DBTX, arg AddTranscriptParams) (CallTranscript, error)
	CreateCall(ctx context.Context, db DBTX) (CallCall, error)
	EndCall(ctx context.Context, db DBTX, id uuid.UUID) error
	GetCallByID(ctx context.Context, db DBTX, id uuid.UUID) (GetCallByIDRow, error)
	GetCallHistory(ctx context.Context, db DBTX, arg GetCallHistoryParams) ([]GetCallHistoryRow, error)
	GetCallParticipants(ctx context.Context, db DBTX, callID uuid.UUID) ([]GetCallParticipantsRow, error)
	GetCallTranscripts(ctx context.Context, db DBTX, callID uuid.UUID) ([]GetCallTranscriptsRow, error)
	GetUserCalls(ctx context.Context, db DBTX, userID uuid.UUID) ([]GetUserCallsRow, error)
	UpdateParticipantLeftAt(ctx context.Context, db DBTX, arg UpdateParticipantLeftAtParams) error
}

var _ Querier = (*Queries)(nil)
