// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cv

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CvCv struct {
	Guid      uuid.UUID
	UserGuid  string
	Link      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type CvResumeDatabase struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	CandidateName   string
	CandidateAge    sql.NullInt32
	ExperienceYears string
	FileUrl         string
	Analysis        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
