// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cv

import (
	"database/sql"

	"github.com/google/uuid"
)

type CvCv struct {
	Guid      uuid.UUID
	UserGuid  string
	Link      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
