// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cv

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCV(ctx context.Context, db DBTX, arg CreateCVParams) (CvCv, error)
	DeleteCV(ctx context.Context, db DBTX, guid uuid.UUID) error
	GetCVByGUID(ctx context.Context, db DBTX, guid uuid.UUID) (CvCv, error)
	GetCVByUserGUID(ctx context.Context, db DBTX, userGuid string) (CvCv, error)
	UpdateCV(ctx context.Context, db DBTX, arg UpdateCVParams) (CvCv, error)
}

var _ Querier = (*Queries)(nil)
