// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package profile

import (
	"database/sql"

	"github.com/google/uuid"
)

type CompanyProfileCompany struct {
	UserGuid    uuid.UUID
	CompanyGuid uuid.UUID
	Position    string
	StartedAt   sql.NullTime
	FinishedAt  sql.NullTime
	Guid        uuid.UUID
}

type ProfileProfile struct {
	Guid              uuid.UUID
	IsHr              sql.NullBool
	Description       string
	Email             string
	Phone             sql.NullString
	Gender            string
	Birthday          string
	Avatar            sql.NullString
	PasswordHash      string
	IsActive          bool
	VerificationToken sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}
