// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package profile

import (
	"database/sql"

	"github.com/google/uuid"
)

type CompanyProfileCompany struct {
	UserGuid    uuid.UUID
	CompanyGuid uuid.UUID
	Position    string
	StartedAt   sql.NullTime
	FinishedAt  sql.NullTime
}

type ProfileProfile struct {
	Guid        uuid.UUID
	IsHr        sql.NullBool
	Description string
	Email       sql.NullString
	Phone       sql.NullString
	Gender      string
	Birthday    string
	Avatar      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
