// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package profile

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProfile(ctx context.Context, db DBTX, arg CreateProfileParams) (ProfileProfile, error)
	DeleteProfile(ctx context.Context, db DBTX, guid uuid.UUID) error
	GetProfileByEmail(ctx context.Context, db DBTX, email string) (ProfileProfile, error)
	GetProfileByGUID(ctx context.Context, db DBTX, guid uuid.UUID) (ProfileProfile, error)
	GetProfileCompanies(ctx context.Context, db DBTX, userGuid uuid.UUID) ([]CompanyProfileCompany, error)
	SearchProfiles(ctx context.Context, db DBTX, dollar_1 sql.NullString) ([]ProfileProfile, error)
	UpdateProfile(ctx context.Context, db DBTX, arg UpdateProfileParams) (ProfileProfile, error)
	UpdateProfileCompany(ctx context.Context, db DBTX, arg UpdateProfileCompanyParams) (CompanyProfileCompany, error)
}

var _ Querier = (*Queries)(nil)
