openapi: 3.0.0
info:
  title: HROpenPlatform Chat OpenAPI 3.1.0 specification
  description: HROpenPlatform Chat OpenAPI 3.1.0 specification
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
paths:
  /api/v1/chat:
    get:
      tags:
        - chat
      operationId: getUserChats
      summary: Get user chats
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatWithLastMessage'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      tags:
        - chat
      summary: Create new chat
      operationId: createChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatRequest'
      responses:
        '201':
          description: Chat created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/chat/{chat_id}/messages:
    get:
      tags:
        - chat
      operationId: getChatMessages
      summary: Get chat messages
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Chat not found
        '500':
          description: Internal Server Error
    post:
      tags:
        - chat
      operationId: sendMessage
      summary: Send message
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
        '404':
          description: Chat not found
        '500':
          description: Internal Server Error

  /api/v1/chat/{chat_id}/ws:
    get:
      tags:
        - chat
      operationId: handleWebSocket
      summary: WebSocket connection for real-time chat
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '101':
          description: Switching Protocols
        '401':
          description: Unauthorized
        '404':
          description: Chat not found

components:
  schemas:
    Chat:
      type: object
      required:
        - id
        - users
        - created_at
        - updated_at
      properties:
        id:
          type: string
        users:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Message:
      type: object
      required:
        - id
        - chat_id
        - user_id
        - text
        - created_at
      properties:
        id:
          type: string
        chat_id:
          type: string
        user_id:
          type: string
        text:
          type: string
        created_at:
          type: string
          format: date-time

    ChatWithLastMessage:
      type: object
      required:
        - chat
        - unread_count
      properties:
        chat:
          $ref: '#/components/schemas/Chat'
        last_message:
          $ref: '#/components/schemas/Message'
        unread_count:
          type: integer

    CreateChatRequest:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          items:
            type: string

    SendMessageRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string 