openapi: 3.0.0
info:
  title: HROpenPlatform CV OpenAPI 3.1.0 specification
  description: HROpenPlatform CV OpenAPI 3.1.0 specification
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
paths:
  /api/v1/cv/upload:
    post:
      tags:
        - cv
      summary: Загрузить резюме
      operationId: uploadCV
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUploadCVResp'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

components:
  schemas:
    ApiUploadCVResp:
      type: object
      required:
        - link
      properties:
        link:
          type: string
          description: Ссылка на загруженное резюме

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
