openapi: 3.0.0
info:
  title: HROpenPlatform Job OpenAPI 3.1.0 specification
  description: HROpenPlatform Job OpenAPI 3.1.0 specification
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
paths:
  /api/v1/job:
    get:
      tags:
        - job
      summary: Get all jobs with search
      operationId: getAllJobs
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '500':
          description: Internal Server Error

    post:
      tags:
        - job
      summary: Create new job
      operationId: createJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
      responses:
        '201':
          description: Job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/job/my:
    get:
      tags:
        - job
      summary: Get my published jobs
      operationId: getMyJobs
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobWithApplications'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/job/{job_id}:
    get:
      tags:
        - job
      summary: Get job by ID
      operationId: getJobById
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobDetails'
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - job
      summary: Update job
      operationId: updateJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
      responses:
        '200':
          description: Job updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

    delete:
      tags:
        - job
      summary: Delete job
      operationId: deleteJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Job deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

  /api/v1/job/{job_id}/apply:
    post:
      tags:
        - job
      summary: Apply to job
      operationId: applyToJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Application submitted
        '400':
          description: Already applied
        '401':
          description: Unauthorized
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

    get:
      tags:
        - job
      summary: Check application status
      operationId: getApplicationStatus
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationStatus'
        '401':
          description: Unauthorized
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

  /api/v1/job/{job_id}/applications:
    get:
      tags:
        - job
      summary: Get job applications (for job author)
      operationId: getJobApplications
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobApplication'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

  /api/v1/job/{job_id}/applications/{applicant_id}/status:
    put:
      tags:
        - job
      summary: Update job application status (for job author)
      operationId: updateJobApplicationStatus
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
        - name: applicant_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateApplicationStatusRequest'
      responses:
        '200':
          description: Application status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplication'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Job or application not found
        '500':
          description: Internal Server Error

components:
  schemas:
    Job:
      type: object
      required:
        - id
        - title
        - company_name
        - location
        - employment_type
        - salary_from
        - description
        - requirements
        - author_id
        - created_at
        - updated_at
        - status
      properties:
        id:
          type: string
        title:
          type: string
        company_name:
          type: string
        location:
          type: string
        employment_type:
          type: string
          enum: [full-time, part-time, contract, internship, remote]
        salary_from:
          type: integer
          nullable: true
        salary_to:
          type: integer
          nullable: true
        description:
          type: string
        requirements:
          type: string
        author_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, paused, closed]

    JobDetails:
      type: object
      required:
        - job
        - is_author
        - can_apply
        - has_applied
      properties:
        job:
          $ref: '#/components/schemas/Job'
        is_author:
          type: boolean
        can_apply:
          type: boolean
        has_applied:
          type: boolean
        applications:
          type: array
          items:
            $ref: '#/components/schemas/JobApplication'
          nullable: true

    JobWithApplications:
      type: object
      required:
        - job
        - applications_count
      properties:
        job:
          $ref: '#/components/schemas/Job'
        applications_count:
          type: integer

    JobApplication:
      type: object
      required:
        - id
        - job_id
        - applicant_id
        - applicant_profile
        - applied_at
        - status
      properties:
        id:
          type: string
        job_id:
          type: string
        applicant_id:
          type: string
        applicant_profile:
          $ref: '#/components/schemas/ApplicantProfile'
        applied_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [pending, reviewed, accepted, rejected]

    ApplicantProfile:
      type: object
      required:
        - id
        - description
        - email
      properties:
        id:
          type: string
        description:
          type: string
        email:
          type: string
        avatar:
          type: string
          nullable: true

    ApplicationStatus:
      type: object
      required:
        - has_applied
        - application_id
        - status
      properties:
        has_applied:
          type: boolean
        application_id:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, reviewed, accepted, rejected]
          nullable: true

    CreateJobRequest:
      type: object
      required:
        - title
        - company_name
        - location
        - employment_type
        - description
        - requirements
      properties:
        title:
          type: string
        company_name:
          type: string
        location:
          type: string
        employment_type:
          type: string
          enum: [full-time, part-time, contract, internship, remote]
        salary_from:
          type: integer
          nullable: true
        salary_to:
          type: integer
          nullable: true
        description:
          type: string
        requirements:
          type: string

    UpdateJobRequest:
      type: object
      required:
        - title
        - company_name
        - location
        - employment_type
        - description
        - requirements
        - status
      properties:
        title:
          type: string
        company_name:
          type: string
        location:
          type: string
        employment_type:
          type: string
          enum: [full-time, part-time, contract, internship, remote]
        salary_from:
          type: integer
          nullable: true
        salary_to:
          type: integer
          nullable: true
        description:
          type: string
        requirements:
          type: string
        status:
          type: string
          enum: [active, paused, closed]

    UpdateApplicationStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [pending, reviewed, accepted, rejected] 